#!/bin/bash
style=$1 && shift

case $style in
	-html)
		sed -e"1i <Table>
		    i <tr><td>
		    s'\t'</td><td>'
		    a </td></tr>
		    \$a </table>" 
		;;
	-tbl)
		fmt=$1 && shift
		sed -e"\
			1i .TS
			1i $fmt
		    1i .
			\$a .TE"	
		;;
	-latex)
		fmt=$1 && shift
		sed -e"1i \\\\\\begin{table}{${fmt:?latex format no set}}
			s'\t'\&'
			s/$/\\\\\\\\/
			\$a \\\\\\end{table}"
		;;
	*)
		echo "not right"
		exit 1
		;;
esac

