#!/bin/bash

a=10
while [ $a -gt 0 ]
do
  echo -n "$a "
  ((a--))
done
echo
echo Blast-Off
echo

# A C-like for construct....
for ((a=10; a > 0 ; a--))
do
  echo -n "$a "
done
echo
echo Blast-Off
echo

