#!/bin/bash

date

mkdir src
cp *.c* src
echo Source files copied to src folder

mkdir exc
cp *.x exc
echo Source files copied to exc folder


#  Wait for a key press ...
read -p "Press ENTER to continue"
clear
